DATA:
  data_root: ../../Dataset/Pascal_Context/
  train_list: data/voc2010/list/train.txt
  val_list: data/voc2010/list/val.txt
  classes: 60

TRAIN:
  arch: baseg
  layers: 101
  sync_bn: False  # adopt sync_bn or not
  train_h: 480
  train_w: 480
  multi_grid: [1, 1, 1]
  in_channels: [256, 512, 1024, 2048]
  depth: [1]
  embed_dim: 512
  ohem: False
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 0 
  seg_weight: 1.0
  edge_weight: 8.0
  att_weight: 0.0
  aux_weight: 0.4
  train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 4  # batch size for training
  batch_size_val: 4  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.001
  epochs: 150
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 10
  save_path: exp/voc2010/baseg101/model/baseline_aspp_canny_edge_lre3
  weight:  #
  resume:  # 
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: data/voc2010/list/val.txt
  split: val  # split in [train, val and test]
  base_size: 2048  # based size for scaling
  test_h: 480
  test_w: 480
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: exp/voc2010/baseg101/model/baseline_aspp_canny_edge_lre3/train_epoch_100.pth  # evaluation model path
  save_folder: exp/voc2010/baseg101/result/baseline_aspp_canny_edge_lre3/ss  # results save folder
  colors_path: data/voc2010/voc2010_colors.txt  # path of dataset colors
  names_path: data/voc2010/voc2010_names.txt  # path of dataset category names
