DATA:
  data_root: ../../Dataset/Cityscapes/
  train_list: data/cityscapes/list/fine_train.txt
  val_list: data/cityscapes/list/fine_val.txt
  classes: 19

TRAIN:
  arch: baseg
  layers: 101
  sync_bn: True  # adopt sync_bn or not
  train_h: 769
  train_w: 769
  multi_grid: [1, 1, 1]
  in_channels: [256, 512, 1024, 2048]
  depth: [1]
  embed_dim: 512
  ohem: False
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  seg_weight: 1.0
  edge_weight: 8.0
  att_weight: 0.0
  aux_weight: 0.4
  train_gpu: [0, 1, 2, 3]
  workers: 12  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.001
  epochs: 200
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0005
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/cityscapes/baseg101/model/baseline_aspp_canny_gate_lre2_flohem_tv3
  weight:  # path to initial weight (default: none)
  resume:  # exp/cityscapes/baseg101/model/baseline_aspp_edge_gate_lre3/train_epoch_111.pth
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: data/cityscapes/list/fine_test.txt
  split: test  # split in [train, val and test]
  base_size: 2048  # based size for scaling
  test_h: 769
  test_w: 769
  scales: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: exp/cityscapes/baseg101/model/baseline_aspp_canny_gate_lre2_flohem_tv3/train_epoch_291.pth  # evaluation model path
  save_folder: exp/cityscapes/baseg101/result/baseline_aspp_canny_gate_lre2_flohem_tv3/ms/test/  # results save folder
  colors_path: data/cityscapes/cityscapes_colors.txt  # path of dataset colors
  names_path: data/cityscapes/cityscapes_names.txt  # path of dataset category names
